// Code generated by go-swagger; DO NOT EDIT.

package routing_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/buyer/models"
)

// NewCreateRoutingInstanceUsingPOSTParams creates a new CreateRoutingInstanceUsingPOSTParams object
// with the default values initialized.
func NewCreateRoutingInstanceUsingPOSTParams() *CreateRoutingInstanceUsingPOSTParams {
	var ()
	return &CreateRoutingInstanceUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRoutingInstanceUsingPOSTParamsWithTimeout creates a new CreateRoutingInstanceUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRoutingInstanceUsingPOSTParamsWithTimeout(timeout time.Duration) *CreateRoutingInstanceUsingPOSTParams {
	var ()
	return &CreateRoutingInstanceUsingPOSTParams{

		timeout: timeout,
	}
}

// NewCreateRoutingInstanceUsingPOSTParamsWithContext creates a new CreateRoutingInstanceUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRoutingInstanceUsingPOSTParamsWithContext(ctx context.Context) *CreateRoutingInstanceUsingPOSTParams {
	var ()
	return &CreateRoutingInstanceUsingPOSTParams{

		Context: ctx,
	}
}

// NewCreateRoutingInstanceUsingPOSTParamsWithHTTPClient creates a new CreateRoutingInstanceUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRoutingInstanceUsingPOSTParamsWithHTTPClient(client *http.Client) *CreateRoutingInstanceUsingPOSTParams {
	var ()
	return &CreateRoutingInstanceUsingPOSTParams{
		HTTPClient: client,
	}
}

/*CreateRoutingInstanceUsingPOSTParams contains all the parameters to send to the API endpoint
for the create routing instance using p o s t operation typically these are written to a http.Request
*/
type CreateRoutingInstanceUsingPOSTParams struct {

	/*Authorization
	  Specify the OAuth Bearer token with prefix 'Bearer '.

	*/
	Authorization string
	/*Request
	  request

	*/
	Request *models.RoutingInstanceCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) WithTimeout(timeout time.Duration) *CreateRoutingInstanceUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) WithContext(ctx context.Context) *CreateRoutingInstanceUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) WithHTTPClient(client *http.Client) *CreateRoutingInstanceUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) WithAuthorization(authorization string) *CreateRoutingInstanceUsingPOSTParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithRequest adds the request to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) WithRequest(request *models.RoutingInstanceCreateRequest) *CreateRoutingInstanceUsingPOSTParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create routing instance using p o s t params
func (o *CreateRoutingInstanceUsingPOSTParams) SetRequest(request *models.RoutingInstanceCreateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRoutingInstanceUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
