// Code generated by go-swagger; DO NOT EDIT.

package routing_instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRoutingInstanceUsingDELETEParams creates a new DeleteRoutingInstanceUsingDELETEParams object
// with the default values initialized.
func NewDeleteRoutingInstanceUsingDELETEParams() *DeleteRoutingInstanceUsingDELETEParams {
	var ()
	return &DeleteRoutingInstanceUsingDELETEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRoutingInstanceUsingDELETEParamsWithTimeout creates a new DeleteRoutingInstanceUsingDELETEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRoutingInstanceUsingDELETEParamsWithTimeout(timeout time.Duration) *DeleteRoutingInstanceUsingDELETEParams {
	var ()
	return &DeleteRoutingInstanceUsingDELETEParams{

		timeout: timeout,
	}
}

// NewDeleteRoutingInstanceUsingDELETEParamsWithContext creates a new DeleteRoutingInstanceUsingDELETEParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRoutingInstanceUsingDELETEParamsWithContext(ctx context.Context) *DeleteRoutingInstanceUsingDELETEParams {
	var ()
	return &DeleteRoutingInstanceUsingDELETEParams{

		Context: ctx,
	}
}

// NewDeleteRoutingInstanceUsingDELETEParamsWithHTTPClient creates a new DeleteRoutingInstanceUsingDELETEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRoutingInstanceUsingDELETEParamsWithHTTPClient(client *http.Client) *DeleteRoutingInstanceUsingDELETEParams {
	var ()
	return &DeleteRoutingInstanceUsingDELETEParams{
		HTTPClient: client,
	}
}

/*DeleteRoutingInstanceUsingDELETEParams contains all the parameters to send to the API endpoint
for the delete routing instance using d e l e t e operation typically these are written to a http.Request
*/
type DeleteRoutingInstanceUsingDELETEParams struct {

	/*Authorization
	  Specify the OAuth Bearer token with prefix 'Bearer '.

	*/
	Authorization string
	/*UUID
	  uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) WithTimeout(timeout time.Duration) *DeleteRoutingInstanceUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) WithContext(ctx context.Context) *DeleteRoutingInstanceUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) WithHTTPClient(client *http.Client) *DeleteRoutingInstanceUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) WithAuthorization(authorization string) *DeleteRoutingInstanceUsingDELETEParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithUUID adds the uuid to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) WithUUID(uuid string) *DeleteRoutingInstanceUsingDELETEParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete routing instance using d e l e t e params
func (o *DeleteRoutingInstanceUsingDELETEParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRoutingInstanceUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
