// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// CreateServiceProfilesUsingPOSTReader is a Reader for the CreateServiceProfilesUsingPOST structure.
type CreateServiceProfilesUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateServiceProfilesUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateServiceProfilesUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewCreateServiceProfilesUsingPOSTNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateServiceProfilesUsingPOSTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateServiceProfilesUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateServiceProfilesUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewCreateServiceProfilesUsingPOSTMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewCreateServiceProfilesUsingPOSTConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateServiceProfilesUsingPOSTInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewCreateServiceProfilesUsingPOSTServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateServiceProfilesUsingPOSTCreated creates a CreateServiceProfilesUsingPOSTCreated with default headers values
func NewCreateServiceProfilesUsingPOSTCreated() *CreateServiceProfilesUsingPOSTCreated {
	return &CreateServiceProfilesUsingPOSTCreated{}
}

/*CreateServiceProfilesUsingPOSTCreated handles this case with default header values.

created
*/
type CreateServiceProfilesUsingPOSTCreated struct {
	Payload *models.ServiceProfilesCreateResponse
}

func (o *CreateServiceProfilesUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTCreated  %+v", 201, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProfilesCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceProfilesUsingPOSTNoContent creates a CreateServiceProfilesUsingPOSTNoContent with default headers values
func NewCreateServiceProfilesUsingPOSTNoContent() *CreateServiceProfilesUsingPOSTNoContent {
	return &CreateServiceProfilesUsingPOSTNoContent{}
}

/*CreateServiceProfilesUsingPOSTNoContent handles this case with default header values.

No Content
*/
type CreateServiceProfilesUsingPOSTNoContent struct {
}

func (o *CreateServiceProfilesUsingPOSTNoContent) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTNoContent ", 204)
}

func (o *CreateServiceProfilesUsingPOSTNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateServiceProfilesUsingPOSTBadRequest creates a CreateServiceProfilesUsingPOSTBadRequest with default headers values
func NewCreateServiceProfilesUsingPOSTBadRequest() *CreateServiceProfilesUsingPOSTBadRequest {
	return &CreateServiceProfilesUsingPOSTBadRequest{}
}

/*CreateServiceProfilesUsingPOSTBadRequest handles this case with default header values.

Bad request
*/
type CreateServiceProfilesUsingPOSTBadRequest struct {
	Payload models.GeneralErrorMessage
}

func (o *CreateServiceProfilesUsingPOSTBadRequest) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTBadRequest  %+v", 400, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceProfilesUsingPOSTUnauthorized creates a CreateServiceProfilesUsingPOSTUnauthorized with default headers values
func NewCreateServiceProfilesUsingPOSTUnauthorized() *CreateServiceProfilesUsingPOSTUnauthorized {
	return &CreateServiceProfilesUsingPOSTUnauthorized{}
}

/*CreateServiceProfilesUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateServiceProfilesUsingPOSTUnauthorized struct {
	Payload models.GeneralErrorMessage
}

func (o *CreateServiceProfilesUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceProfilesUsingPOSTForbidden creates a CreateServiceProfilesUsingPOSTForbidden with default headers values
func NewCreateServiceProfilesUsingPOSTForbidden() *CreateServiceProfilesUsingPOSTForbidden {
	return &CreateServiceProfilesUsingPOSTForbidden{}
}

/*CreateServiceProfilesUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type CreateServiceProfilesUsingPOSTForbidden struct {
	Payload models.GeneralErrorMessage
}

func (o *CreateServiceProfilesUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTForbidden  %+v", 403, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceProfilesUsingPOSTMethodNotAllowed creates a CreateServiceProfilesUsingPOSTMethodNotAllowed with default headers values
func NewCreateServiceProfilesUsingPOSTMethodNotAllowed() *CreateServiceProfilesUsingPOSTMethodNotAllowed {
	return &CreateServiceProfilesUsingPOSTMethodNotAllowed{}
}

/*CreateServiceProfilesUsingPOSTMethodNotAllowed handles this case with default header values.

Method Not Allowed
*/
type CreateServiceProfilesUsingPOSTMethodNotAllowed struct {
	Payload models.GeneralErrorMessage
}

func (o *CreateServiceProfilesUsingPOSTMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceProfilesUsingPOSTConflict creates a CreateServiceProfilesUsingPOSTConflict with default headers values
func NewCreateServiceProfilesUsingPOSTConflict() *CreateServiceProfilesUsingPOSTConflict {
	return &CreateServiceProfilesUsingPOSTConflict{}
}

/*CreateServiceProfilesUsingPOSTConflict handles this case with default header values.

Conflict
*/
type CreateServiceProfilesUsingPOSTConflict struct {
	Payload models.GeneralErrorMessage
}

func (o *CreateServiceProfilesUsingPOSTConflict) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTConflict  %+v", 409, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceProfilesUsingPOSTInternalServerError creates a CreateServiceProfilesUsingPOSTInternalServerError with default headers values
func NewCreateServiceProfilesUsingPOSTInternalServerError() *CreateServiceProfilesUsingPOSTInternalServerError {
	return &CreateServiceProfilesUsingPOSTInternalServerError{}
}

/*CreateServiceProfilesUsingPOSTInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreateServiceProfilesUsingPOSTInternalServerError struct {
	Payload models.GeneralErrorMessage
}

func (o *CreateServiceProfilesUsingPOSTInternalServerError) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceProfilesUsingPOSTServiceUnavailable creates a CreateServiceProfilesUsingPOSTServiceUnavailable with default headers values
func NewCreateServiceProfilesUsingPOSTServiceUnavailable() *CreateServiceProfilesUsingPOSTServiceUnavailable {
	return &CreateServiceProfilesUsingPOSTServiceUnavailable{}
}

/*CreateServiceProfilesUsingPOSTServiceUnavailable handles this case with default header values.

Service Unavailable
*/
type CreateServiceProfilesUsingPOSTServiceUnavailable struct {
	Payload models.GeneralErrorMessage
}

func (o *CreateServiceProfilesUsingPOSTServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l3/serviceprofiles][%d] createServiceProfilesUsingPOSTServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CreateServiceProfilesUsingPOSTServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
