// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// NewCreateServiceProfilesUsingPOSTParams creates a new CreateServiceProfilesUsingPOSTParams object
// with the default values initialized.
func NewCreateServiceProfilesUsingPOSTParams() *CreateServiceProfilesUsingPOSTParams {
	var ()
	return &CreateServiceProfilesUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateServiceProfilesUsingPOSTParamsWithTimeout creates a new CreateServiceProfilesUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateServiceProfilesUsingPOSTParamsWithTimeout(timeout time.Duration) *CreateServiceProfilesUsingPOSTParams {
	var ()
	return &CreateServiceProfilesUsingPOSTParams{

		timeout: timeout,
	}
}

// NewCreateServiceProfilesUsingPOSTParamsWithContext creates a new CreateServiceProfilesUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateServiceProfilesUsingPOSTParamsWithContext(ctx context.Context) *CreateServiceProfilesUsingPOSTParams {
	var ()
	return &CreateServiceProfilesUsingPOSTParams{

		Context: ctx,
	}
}

// NewCreateServiceProfilesUsingPOSTParamsWithHTTPClient creates a new CreateServiceProfilesUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateServiceProfilesUsingPOSTParamsWithHTTPClient(client *http.Client) *CreateServiceProfilesUsingPOSTParams {
	var ()
	return &CreateServiceProfilesUsingPOSTParams{
		HTTPClient: client,
	}
}

/*CreateServiceProfilesUsingPOSTParams contains all the parameters to send to the API endpoint
for the create service profiles using p o s t operation typically these are written to a http.Request
*/
type CreateServiceProfilesUsingPOSTParams struct {

	/*Authorization
	  Specify the OAuth Bearer token with prefix 'Bearer '.

	*/
	Authorization string
	/*Request
	  request

	*/
	Request *models.ServiceProfilesCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) WithTimeout(timeout time.Duration) *CreateServiceProfilesUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) WithContext(ctx context.Context) *CreateServiceProfilesUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) WithHTTPClient(client *http.Client) *CreateServiceProfilesUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) WithAuthorization(authorization string) *CreateServiceProfilesUsingPOSTParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithRequest adds the request to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) WithRequest(request *models.ServiceProfilesCreateRequest) *CreateServiceProfilesUsingPOSTParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create service profiles using p o s t params
func (o *CreateServiceProfilesUsingPOSTParams) SetRequest(request *models.ServiceProfilesCreateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateServiceProfilesUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
