// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// DeleteProfileByProfileNameOrUUIDUsingDELETEReader is a Reader for the DeleteProfileByProfileNameOrUUIDUsingDELETE structure.
type DeleteProfileByProfileNameOrUUIDUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProfileByProfileNameOrUUIDUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteProfileByProfileNameOrUUIDUsingDELETEOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewDeleteProfileByProfileNameOrUUIDUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewDeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProfileByProfileNameOrUUIDUsingDELETEOK creates a DeleteProfileByProfileNameOrUUIDUsingDELETEOK with default headers values
func NewDeleteProfileByProfileNameOrUUIDUsingDELETEOK() *DeleteProfileByProfileNameOrUUIDUsingDELETEOK {
	return &DeleteProfileByProfileNameOrUUIDUsingDELETEOK{}
}

/*DeleteProfileByProfileNameOrUUIDUsingDELETEOK handles this case with default header values.

Success
*/
type DeleteProfileByProfileNameOrUUIDUsingDELETEOK struct {
	Payload *models.DeleteServiceProfileResponse
}

func (o *DeleteProfileByProfileNameOrUUIDUsingDELETEOK) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l2/serviceprofiles/{uuid}][%d] deleteProfileByProfileNameOrUuidUsingDELETEOK  %+v", 200, o.Payload)
}

func (o *DeleteProfileByProfileNameOrUUIDUsingDELETEOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteServiceProfileResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByProfileNameOrUUIDUsingDELETENoContent creates a DeleteProfileByProfileNameOrUUIDUsingDELETENoContent with default headers values
func NewDeleteProfileByProfileNameOrUUIDUsingDELETENoContent() *DeleteProfileByProfileNameOrUUIDUsingDELETENoContent {
	return &DeleteProfileByProfileNameOrUUIDUsingDELETENoContent{}
}

/*DeleteProfileByProfileNameOrUUIDUsingDELETENoContent handles this case with default header values.

Record Not Found
*/
type DeleteProfileByProfileNameOrUUIDUsingDELETENoContent struct {
	Payload *models.ErrorResponse
}

func (o *DeleteProfileByProfileNameOrUUIDUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l2/serviceprofiles/{uuid}][%d] deleteProfileByProfileNameOrUuidUsingDELETENoContent  %+v", 204, o.Payload)
}

func (o *DeleteProfileByProfileNameOrUUIDUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError creates a DeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError with default headers values
func NewDeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError() *DeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError {
	return &DeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError{}
}

/*DeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l2/serviceprofiles/{uuid}][%d] deleteProfileByProfileNameOrUuidUsingDELETEInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteProfileByProfileNameOrUUIDUsingDELETEInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
