// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// DeleteProfileByIDUsingDELETEReader is a Reader for the DeleteProfileByIDUsingDELETE structure.
type DeleteProfileByIDUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProfileByIDUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteProfileByIDUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteProfileByIDUsingDELETEBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteProfileByIDUsingDELETEUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteProfileByIDUsingDELETEForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewDeleteProfileByIDUsingDELETEMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewDeleteProfileByIDUsingDELETEConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteProfileByIDUsingDELETEInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewDeleteProfileByIDUsingDELETEServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProfileByIDUsingDELETENoContent creates a DeleteProfileByIDUsingDELETENoContent with default headers values
func NewDeleteProfileByIDUsingDELETENoContent() *DeleteProfileByIDUsingDELETENoContent {
	return &DeleteProfileByIDUsingDELETENoContent{}
}

/*DeleteProfileByIDUsingDELETENoContent handles this case with default header values.

Success
*/
type DeleteProfileByIDUsingDELETENoContent struct {
}

func (o *DeleteProfileByIDUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETENoContent ", 204)
}

func (o *DeleteProfileByIDUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProfileByIDUsingDELETEBadRequest creates a DeleteProfileByIDUsingDELETEBadRequest with default headers values
func NewDeleteProfileByIDUsingDELETEBadRequest() *DeleteProfileByIDUsingDELETEBadRequest {
	return &DeleteProfileByIDUsingDELETEBadRequest{}
}

/*DeleteProfileByIDUsingDELETEBadRequest handles this case with default header values.

Bad request
*/
type DeleteProfileByIDUsingDELETEBadRequest struct {
	Payload models.GeneralErrorMessage
}

func (o *DeleteProfileByIDUsingDELETEBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETEBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteProfileByIDUsingDELETEBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByIDUsingDELETEUnauthorized creates a DeleteProfileByIDUsingDELETEUnauthorized with default headers values
func NewDeleteProfileByIDUsingDELETEUnauthorized() *DeleteProfileByIDUsingDELETEUnauthorized {
	return &DeleteProfileByIDUsingDELETEUnauthorized{}
}

/*DeleteProfileByIDUsingDELETEUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteProfileByIDUsingDELETEUnauthorized struct {
	Payload models.GeneralErrorMessage
}

func (o *DeleteProfileByIDUsingDELETEUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETEUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteProfileByIDUsingDELETEUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByIDUsingDELETEForbidden creates a DeleteProfileByIDUsingDELETEForbidden with default headers values
func NewDeleteProfileByIDUsingDELETEForbidden() *DeleteProfileByIDUsingDELETEForbidden {
	return &DeleteProfileByIDUsingDELETEForbidden{}
}

/*DeleteProfileByIDUsingDELETEForbidden handles this case with default header values.

Forbidden
*/
type DeleteProfileByIDUsingDELETEForbidden struct {
	Payload models.GeneralErrorMessage
}

func (o *DeleteProfileByIDUsingDELETEForbidden) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETEForbidden  %+v", 403, o.Payload)
}

func (o *DeleteProfileByIDUsingDELETEForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByIDUsingDELETEMethodNotAllowed creates a DeleteProfileByIDUsingDELETEMethodNotAllowed with default headers values
func NewDeleteProfileByIDUsingDELETEMethodNotAllowed() *DeleteProfileByIDUsingDELETEMethodNotAllowed {
	return &DeleteProfileByIDUsingDELETEMethodNotAllowed{}
}

/*DeleteProfileByIDUsingDELETEMethodNotAllowed handles this case with default header values.

Method Not Allowed
*/
type DeleteProfileByIDUsingDELETEMethodNotAllowed struct {
	Payload models.GeneralErrorMessage
}

func (o *DeleteProfileByIDUsingDELETEMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETEMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *DeleteProfileByIDUsingDELETEMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByIDUsingDELETEConflict creates a DeleteProfileByIDUsingDELETEConflict with default headers values
func NewDeleteProfileByIDUsingDELETEConflict() *DeleteProfileByIDUsingDELETEConflict {
	return &DeleteProfileByIDUsingDELETEConflict{}
}

/*DeleteProfileByIDUsingDELETEConflict handles this case with default header values.

Conflict
*/
type DeleteProfileByIDUsingDELETEConflict struct {
	Payload models.GeneralErrorMessage
}

func (o *DeleteProfileByIDUsingDELETEConflict) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETEConflict  %+v", 409, o.Payload)
}

func (o *DeleteProfileByIDUsingDELETEConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByIDUsingDELETEInternalServerError creates a DeleteProfileByIDUsingDELETEInternalServerError with default headers values
func NewDeleteProfileByIDUsingDELETEInternalServerError() *DeleteProfileByIDUsingDELETEInternalServerError {
	return &DeleteProfileByIDUsingDELETEInternalServerError{}
}

/*DeleteProfileByIDUsingDELETEInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteProfileByIDUsingDELETEInternalServerError struct {
	Payload models.GeneralErrorMessage
}

func (o *DeleteProfileByIDUsingDELETEInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETEInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteProfileByIDUsingDELETEInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProfileByIDUsingDELETEServiceUnavailable creates a DeleteProfileByIDUsingDELETEServiceUnavailable with default headers values
func NewDeleteProfileByIDUsingDELETEServiceUnavailable() *DeleteProfileByIDUsingDELETEServiceUnavailable {
	return &DeleteProfileByIDUsingDELETEServiceUnavailable{}
}

/*DeleteProfileByIDUsingDELETEServiceUnavailable handles this case with default header values.

Service Unavailable
*/
type DeleteProfileByIDUsingDELETEServiceUnavailable struct {
	Payload models.GeneralErrorMessage
}

func (o *DeleteProfileByIDUsingDELETEServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /ecx/v3/l3/serviceprofiles/{uuid}][%d] deleteProfileByIdUsingDELETEServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteProfileByIDUsingDELETEServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
