// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// EditL3ServiceProfileUsingPUTReader is a Reader for the EditL3ServiceProfileUsingPUT structure.
type EditL3ServiceProfileUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EditL3ServiceProfileUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEditL3ServiceProfileUsingPUTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewEditL3ServiceProfileUsingPUTNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEditL3ServiceProfileUsingPUTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewEditL3ServiceProfileUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewEditL3ServiceProfileUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewEditL3ServiceProfileUsingPUTMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewEditL3ServiceProfileUsingPUTConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewEditL3ServiceProfileUsingPUTInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewEditL3ServiceProfileUsingPUTServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewEditL3ServiceProfileUsingPUTOK creates a EditL3ServiceProfileUsingPUTOK with default headers values
func NewEditL3ServiceProfileUsingPUTOK() *EditL3ServiceProfileUsingPUTOK {
	return &EditL3ServiceProfileUsingPUTOK{}
}

/*EditL3ServiceProfileUsingPUTOK handles this case with default header values.

success
*/
type EditL3ServiceProfileUsingPUTOK struct {
	Payload *models.PutServiceProfileModelv3
}

func (o *EditL3ServiceProfileUsingPUTOK) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTOK  %+v", 200, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PutServiceProfileModelv3)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditL3ServiceProfileUsingPUTNoContent creates a EditL3ServiceProfileUsingPUTNoContent with default headers values
func NewEditL3ServiceProfileUsingPUTNoContent() *EditL3ServiceProfileUsingPUTNoContent {
	return &EditL3ServiceProfileUsingPUTNoContent{}
}

/*EditL3ServiceProfileUsingPUTNoContent handles this case with default header values.

No Content
*/
type EditL3ServiceProfileUsingPUTNoContent struct {
}

func (o *EditL3ServiceProfileUsingPUTNoContent) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTNoContent ", 204)
}

func (o *EditL3ServiceProfileUsingPUTNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditL3ServiceProfileUsingPUTBadRequest creates a EditL3ServiceProfileUsingPUTBadRequest with default headers values
func NewEditL3ServiceProfileUsingPUTBadRequest() *EditL3ServiceProfileUsingPUTBadRequest {
	return &EditL3ServiceProfileUsingPUTBadRequest{}
}

/*EditL3ServiceProfileUsingPUTBadRequest handles this case with default header values.

Bad request
*/
type EditL3ServiceProfileUsingPUTBadRequest struct {
	Payload models.GeneralErrorMessage
}

func (o *EditL3ServiceProfileUsingPUTBadRequest) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTBadRequest  %+v", 400, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditL3ServiceProfileUsingPUTUnauthorized creates a EditL3ServiceProfileUsingPUTUnauthorized with default headers values
func NewEditL3ServiceProfileUsingPUTUnauthorized() *EditL3ServiceProfileUsingPUTUnauthorized {
	return &EditL3ServiceProfileUsingPUTUnauthorized{}
}

/*EditL3ServiceProfileUsingPUTUnauthorized handles this case with default header values.

Unauthorized
*/
type EditL3ServiceProfileUsingPUTUnauthorized struct {
	Payload models.GeneralErrorMessage
}

func (o *EditL3ServiceProfileUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTUnauthorized  %+v", 401, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditL3ServiceProfileUsingPUTForbidden creates a EditL3ServiceProfileUsingPUTForbidden with default headers values
func NewEditL3ServiceProfileUsingPUTForbidden() *EditL3ServiceProfileUsingPUTForbidden {
	return &EditL3ServiceProfileUsingPUTForbidden{}
}

/*EditL3ServiceProfileUsingPUTForbidden handles this case with default header values.

Forbidden
*/
type EditL3ServiceProfileUsingPUTForbidden struct {
	Payload models.GeneralErrorMessage
}

func (o *EditL3ServiceProfileUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTForbidden  %+v", 403, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditL3ServiceProfileUsingPUTMethodNotAllowed creates a EditL3ServiceProfileUsingPUTMethodNotAllowed with default headers values
func NewEditL3ServiceProfileUsingPUTMethodNotAllowed() *EditL3ServiceProfileUsingPUTMethodNotAllowed {
	return &EditL3ServiceProfileUsingPUTMethodNotAllowed{}
}

/*EditL3ServiceProfileUsingPUTMethodNotAllowed handles this case with default header values.

Method Not Allowed
*/
type EditL3ServiceProfileUsingPUTMethodNotAllowed struct {
	Payload models.GeneralErrorMessage
}

func (o *EditL3ServiceProfileUsingPUTMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditL3ServiceProfileUsingPUTConflict creates a EditL3ServiceProfileUsingPUTConflict with default headers values
func NewEditL3ServiceProfileUsingPUTConflict() *EditL3ServiceProfileUsingPUTConflict {
	return &EditL3ServiceProfileUsingPUTConflict{}
}

/*EditL3ServiceProfileUsingPUTConflict handles this case with default header values.

Conflict
*/
type EditL3ServiceProfileUsingPUTConflict struct {
	Payload models.GeneralErrorMessage
}

func (o *EditL3ServiceProfileUsingPUTConflict) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTConflict  %+v", 409, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditL3ServiceProfileUsingPUTInternalServerError creates a EditL3ServiceProfileUsingPUTInternalServerError with default headers values
func NewEditL3ServiceProfileUsingPUTInternalServerError() *EditL3ServiceProfileUsingPUTInternalServerError {
	return &EditL3ServiceProfileUsingPUTInternalServerError{}
}

/*EditL3ServiceProfileUsingPUTInternalServerError handles this case with default header values.

Internal Server Error
*/
type EditL3ServiceProfileUsingPUTInternalServerError struct {
	Payload models.GeneralErrorMessage
}

func (o *EditL3ServiceProfileUsingPUTInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTInternalServerError  %+v", 500, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditL3ServiceProfileUsingPUTServiceUnavailable creates a EditL3ServiceProfileUsingPUTServiceUnavailable with default headers values
func NewEditL3ServiceProfileUsingPUTServiceUnavailable() *EditL3ServiceProfileUsingPUTServiceUnavailable {
	return &EditL3ServiceProfileUsingPUTServiceUnavailable{}
}

/*EditL3ServiceProfileUsingPUTServiceUnavailable handles this case with default header values.

Service Unavailable
*/
type EditL3ServiceProfileUsingPUTServiceUnavailable struct {
	Payload models.GeneralErrorMessage
}

func (o *EditL3ServiceProfileUsingPUTServiceUnavailable) Error() string {
	return fmt.Sprintf("[PUT /ecx/v3/l3/serviceprofiles/{uuid}][%d] editL3ServiceProfileUsingPUTServiceUnavailable  %+v", 503, o.Payload)
}

func (o *EditL3ServiceProfileUsingPUTServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
