// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// GetAllServiceProfilesUsingGETReader is a Reader for the GetAllServiceProfilesUsingGET structure.
type GetAllServiceProfilesUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllServiceProfilesUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllServiceProfilesUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetAllServiceProfilesUsingGETNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAllServiceProfilesUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAllServiceProfilesUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAllServiceProfilesUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewGetAllServiceProfilesUsingGETMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetAllServiceProfilesUsingGETConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAllServiceProfilesUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetAllServiceProfilesUsingGETServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllServiceProfilesUsingGETOK creates a GetAllServiceProfilesUsingGETOK with default headers values
func NewGetAllServiceProfilesUsingGETOK() *GetAllServiceProfilesUsingGETOK {
	return &GetAllServiceProfilesUsingGETOK{}
}

/*GetAllServiceProfilesUsingGETOK handles this case with default header values.

success
*/
type GetAllServiceProfilesUsingGETOK struct {
	Payload *models.GetServiceProfileL3Response
}

func (o *GetAllServiceProfilesUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetServiceProfileL3Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceProfilesUsingGETNoContent creates a GetAllServiceProfilesUsingGETNoContent with default headers values
func NewGetAllServiceProfilesUsingGETNoContent() *GetAllServiceProfilesUsingGETNoContent {
	return &GetAllServiceProfilesUsingGETNoContent{}
}

/*GetAllServiceProfilesUsingGETNoContent handles this case with default header values.

No Content
*/
type GetAllServiceProfilesUsingGETNoContent struct {
}

func (o *GetAllServiceProfilesUsingGETNoContent) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETNoContent ", 204)
}

func (o *GetAllServiceProfilesUsingGETNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllServiceProfilesUsingGETBadRequest creates a GetAllServiceProfilesUsingGETBadRequest with default headers values
func NewGetAllServiceProfilesUsingGETBadRequest() *GetAllServiceProfilesUsingGETBadRequest {
	return &GetAllServiceProfilesUsingGETBadRequest{}
}

/*GetAllServiceProfilesUsingGETBadRequest handles this case with default header values.

Bad request
*/
type GetAllServiceProfilesUsingGETBadRequest struct {
	Payload models.GeneralErrorMessage
}

func (o *GetAllServiceProfilesUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceProfilesUsingGETUnauthorized creates a GetAllServiceProfilesUsingGETUnauthorized with default headers values
func NewGetAllServiceProfilesUsingGETUnauthorized() *GetAllServiceProfilesUsingGETUnauthorized {
	return &GetAllServiceProfilesUsingGETUnauthorized{}
}

/*GetAllServiceProfilesUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAllServiceProfilesUsingGETUnauthorized struct {
	Payload models.GeneralErrorMessage
}

func (o *GetAllServiceProfilesUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceProfilesUsingGETForbidden creates a GetAllServiceProfilesUsingGETForbidden with default headers values
func NewGetAllServiceProfilesUsingGETForbidden() *GetAllServiceProfilesUsingGETForbidden {
	return &GetAllServiceProfilesUsingGETForbidden{}
}

/*GetAllServiceProfilesUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetAllServiceProfilesUsingGETForbidden struct {
	Payload models.GeneralErrorMessage
}

func (o *GetAllServiceProfilesUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETForbidden  %+v", 403, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceProfilesUsingGETMethodNotAllowed creates a GetAllServiceProfilesUsingGETMethodNotAllowed with default headers values
func NewGetAllServiceProfilesUsingGETMethodNotAllowed() *GetAllServiceProfilesUsingGETMethodNotAllowed {
	return &GetAllServiceProfilesUsingGETMethodNotAllowed{}
}

/*GetAllServiceProfilesUsingGETMethodNotAllowed handles this case with default header values.

Method Not Allowed
*/
type GetAllServiceProfilesUsingGETMethodNotAllowed struct {
	Payload models.GeneralErrorMessage
}

func (o *GetAllServiceProfilesUsingGETMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceProfilesUsingGETConflict creates a GetAllServiceProfilesUsingGETConflict with default headers values
func NewGetAllServiceProfilesUsingGETConflict() *GetAllServiceProfilesUsingGETConflict {
	return &GetAllServiceProfilesUsingGETConflict{}
}

/*GetAllServiceProfilesUsingGETConflict handles this case with default header values.

Conflict
*/
type GetAllServiceProfilesUsingGETConflict struct {
	Payload models.GeneralErrorMessage
}

func (o *GetAllServiceProfilesUsingGETConflict) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETConflict  %+v", 409, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceProfilesUsingGETInternalServerError creates a GetAllServiceProfilesUsingGETInternalServerError with default headers values
func NewGetAllServiceProfilesUsingGETInternalServerError() *GetAllServiceProfilesUsingGETInternalServerError {
	return &GetAllServiceProfilesUsingGETInternalServerError{}
}

/*GetAllServiceProfilesUsingGETInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAllServiceProfilesUsingGETInternalServerError struct {
	Payload models.GeneralErrorMessage
}

func (o *GetAllServiceProfilesUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllServiceProfilesUsingGETServiceUnavailable creates a GetAllServiceProfilesUsingGETServiceUnavailable with default headers values
func NewGetAllServiceProfilesUsingGETServiceUnavailable() *GetAllServiceProfilesUsingGETServiceUnavailable {
	return &GetAllServiceProfilesUsingGETServiceUnavailable{}
}

/*GetAllServiceProfilesUsingGETServiceUnavailable handles this case with default header values.

Service Unavailable
*/
type GetAllServiceProfilesUsingGETServiceUnavailable struct {
	Payload models.GeneralErrorMessage
}

func (o *GetAllServiceProfilesUsingGETServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l3/serviceprofiles][%d] getAllServiceProfilesUsingGETServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetAllServiceProfilesUsingGETServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
