// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// GetProfileByIDOrNameUsingGETReader is a Reader for the GetProfileByIDOrNameUsingGET structure.
type GetProfileByIDOrNameUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProfileByIDOrNameUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProfileByIDOrNameUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetProfileByIDOrNameUsingGETNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetProfileByIDOrNameUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetProfileByIDOrNameUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetProfileByIDOrNameUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProfileByIDOrNameUsingGETOK creates a GetProfileByIDOrNameUsingGETOK with default headers values
func NewGetProfileByIDOrNameUsingGETOK() *GetProfileByIDOrNameUsingGETOK {
	return &GetProfileByIDOrNameUsingGETOK{}
}

/*GetProfileByIDOrNameUsingGETOK handles this case with default header values.

Success
*/
type GetProfileByIDOrNameUsingGETOK struct {
	Payload *models.GetServiceprofilesResContent
}

func (o *GetProfileByIDOrNameUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles/{uuid}][%d] getProfileByIdOrNameUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetProfileByIDOrNameUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetServiceprofilesResContent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfileByIDOrNameUsingGETNoContent creates a GetProfileByIDOrNameUsingGETNoContent with default headers values
func NewGetProfileByIDOrNameUsingGETNoContent() *GetProfileByIDOrNameUsingGETNoContent {
	return &GetProfileByIDOrNameUsingGETNoContent{}
}

/*GetProfileByIDOrNameUsingGETNoContent handles this case with default header values.

No Content
*/
type GetProfileByIDOrNameUsingGETNoContent struct {
}

func (o *GetProfileByIDOrNameUsingGETNoContent) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles/{uuid}][%d] getProfileByIdOrNameUsingGETNoContent ", 204)
}

func (o *GetProfileByIDOrNameUsingGETNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProfileByIDOrNameUsingGETBadRequest creates a GetProfileByIDOrNameUsingGETBadRequest with default headers values
func NewGetProfileByIDOrNameUsingGETBadRequest() *GetProfileByIDOrNameUsingGETBadRequest {
	return &GetProfileByIDOrNameUsingGETBadRequest{}
}

/*GetProfileByIDOrNameUsingGETBadRequest handles this case with default header values.

Bad Request
*/
type GetProfileByIDOrNameUsingGETBadRequest struct {
	Payload models.ErrorResponseArray
}

func (o *GetProfileByIDOrNameUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles/{uuid}][%d] getProfileByIdOrNameUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetProfileByIDOrNameUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfileByIDOrNameUsingGETNotFound creates a GetProfileByIDOrNameUsingGETNotFound with default headers values
func NewGetProfileByIDOrNameUsingGETNotFound() *GetProfileByIDOrNameUsingGETNotFound {
	return &GetProfileByIDOrNameUsingGETNotFound{}
}

/*GetProfileByIDOrNameUsingGETNotFound handles this case with default header values.

Record Not Found
*/
type GetProfileByIDOrNameUsingGETNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetProfileByIDOrNameUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles/{uuid}][%d] getProfileByIdOrNameUsingGETNotFound  %+v", 404, o.Payload)
}

func (o *GetProfileByIDOrNameUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfileByIDOrNameUsingGETInternalServerError creates a GetProfileByIDOrNameUsingGETInternalServerError with default headers values
func NewGetProfileByIDOrNameUsingGETInternalServerError() *GetProfileByIDOrNameUsingGETInternalServerError {
	return &GetProfileByIDOrNameUsingGETInternalServerError{}
}

/*GetProfileByIDOrNameUsingGETInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetProfileByIDOrNameUsingGETInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetProfileByIDOrNameUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles/{uuid}][%d] getProfileByIdOrNameUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *GetProfileByIDOrNameUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
