// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllServiceProfilesUsingGETParams creates a new GetAllServiceProfilesUsingGETParams object
// with the default values initialized.
func NewGetAllServiceProfilesUsingGETParams() *GetAllServiceProfilesUsingGETParams {
	var (
		pageDefault  = int32(0)
		totalDefault = int32(900)
	)
	return &GetAllServiceProfilesUsingGETParams{
		Page:  &pageDefault,
		Total: &totalDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllServiceProfilesUsingGETParamsWithTimeout creates a new GetAllServiceProfilesUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllServiceProfilesUsingGETParamsWithTimeout(timeout time.Duration) *GetAllServiceProfilesUsingGETParams {
	var (
		pageDefault  = int32(0)
		totalDefault = int32(900)
	)
	return &GetAllServiceProfilesUsingGETParams{
		Page:  &pageDefault,
		Total: &totalDefault,

		timeout: timeout,
	}
}

// NewGetAllServiceProfilesUsingGETParamsWithContext creates a new GetAllServiceProfilesUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllServiceProfilesUsingGETParamsWithContext(ctx context.Context) *GetAllServiceProfilesUsingGETParams {
	var (
		pageDefault  = int32(0)
		totalDefault = int32(900)
	)
	return &GetAllServiceProfilesUsingGETParams{
		Page:  &pageDefault,
		Total: &totalDefault,

		Context: ctx,
	}
}

// NewGetAllServiceProfilesUsingGETParamsWithHTTPClient creates a new GetAllServiceProfilesUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllServiceProfilesUsingGETParamsWithHTTPClient(client *http.Client) *GetAllServiceProfilesUsingGETParams {
	var (
		pageDefault  = int32(0)
		totalDefault = int32(900)
	)
	return &GetAllServiceProfilesUsingGETParams{
		Page:       &pageDefault,
		Total:      &totalDefault,
		HTTPClient: client,
	}
}

/*GetAllServiceProfilesUsingGETParams contains all the parameters to send to the API endpoint
for the get all service profiles using g e t operation typically these are written to a http.Request
*/
type GetAllServiceProfilesUsingGETParams struct {

	/*Authorization
	  Specify the OAuth Bearer token with prefix 'Bearer '.

	*/
	Authorization string
	/*Metros
	  metros

	*/
	Metros []string
	/*NoFilterReq
	  noFilterReq

	*/
	NoFilterReq *bool
	/*Page
	  page

	*/
	Page *int32
	/*State
	  state

	*/
	State []string
	/*Total
	  total

	*/
	Total *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithTimeout(timeout time.Duration) *GetAllServiceProfilesUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithContext(ctx context.Context) *GetAllServiceProfilesUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithHTTPClient(client *http.Client) *GetAllServiceProfilesUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithAuthorization(authorization string) *GetAllServiceProfilesUsingGETParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithMetros adds the metros to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithMetros(metros []string) *GetAllServiceProfilesUsingGETParams {
	o.SetMetros(metros)
	return o
}

// SetMetros adds the metros to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetMetros(metros []string) {
	o.Metros = metros
}

// WithNoFilterReq adds the noFilterReq to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithNoFilterReq(noFilterReq *bool) *GetAllServiceProfilesUsingGETParams {
	o.SetNoFilterReq(noFilterReq)
	return o
}

// SetNoFilterReq adds the noFilterReq to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetNoFilterReq(noFilterReq *bool) {
	o.NoFilterReq = noFilterReq
}

// WithPage adds the page to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithPage(page *int32) *GetAllServiceProfilesUsingGETParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetPage(page *int32) {
	o.Page = page
}

// WithState adds the state to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithState(state []string) *GetAllServiceProfilesUsingGETParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetState(state []string) {
	o.State = state
}

// WithTotal adds the total to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) WithTotal(total *int32) *GetAllServiceProfilesUsingGETParams {
	o.SetTotal(total)
	return o
}

// SetTotal adds the total to the get all service profiles using g e t params
func (o *GetAllServiceProfilesUsingGETParams) SetTotal(total *int32) {
	o.Total = total
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllServiceProfilesUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	valuesMetros := o.Metros

	joinedMetros := swag.JoinByFormat(valuesMetros, "")
	// query array param metros
	if err := r.SetQueryParam("metros", joinedMetros...); err != nil {
		return err
	}

	if o.NoFilterReq != nil {

		// query param noFilterReq
		var qrNoFilterReq bool
		if o.NoFilterReq != nil {
			qrNoFilterReq = *o.NoFilterReq
		}
		qNoFilterReq := swag.FormatBool(qrNoFilterReq)
		if qNoFilterReq != "" {
			if err := r.SetQueryParam("noFilterReq", qNoFilterReq); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	valuesState := o.State

	joinedState := swag.JoinByFormat(valuesState, "multi")
	// query array param state
	if err := r.SetQueryParam("state", joinedState...); err != nil {
		return err
	}

	if o.Total != nil {

		// query param total
		var qrTotal int32
		if o.Total != nil {
			qrTotal = *o.Total
		}
		qTotal := swag.FormatInt32(qrTotal)
		if qTotal != "" {
			if err := r.SetQueryParam("total", qTotal); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
