// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/seller/models"
)

// GetAllSellerProfileUsingGETReader is a Reader for the GetAllSellerProfileUsingGET structure.
type GetAllSellerProfileUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllSellerProfileUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllSellerProfileUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetAllSellerProfileUsingGETNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAllSellerProfileUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAllSellerProfileUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetAllSellerProfileUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllSellerProfileUsingGETOK creates a GetAllSellerProfileUsingGETOK with default headers values
func NewGetAllSellerProfileUsingGETOK() *GetAllSellerProfileUsingGETOK {
	return &GetAllSellerProfileUsingGETOK{}
}

/*GetAllSellerProfileUsingGETOK handles this case with default header values.

Success
*/
type GetAllSellerProfileUsingGETOK struct {
	Payload *models.GetServiceprofilesResp
}

func (o *GetAllSellerProfileUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles][%d] getAllSellerProfileUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetAllSellerProfileUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetServiceprofilesResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllSellerProfileUsingGETNoContent creates a GetAllSellerProfileUsingGETNoContent with default headers values
func NewGetAllSellerProfileUsingGETNoContent() *GetAllSellerProfileUsingGETNoContent {
	return &GetAllSellerProfileUsingGETNoContent{}
}

/*GetAllSellerProfileUsingGETNoContent handles this case with default header values.

Record Not Found
*/
type GetAllSellerProfileUsingGETNoContent struct {
	Payload *models.ErrorResponse
}

func (o *GetAllSellerProfileUsingGETNoContent) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles][%d] getAllSellerProfileUsingGETNoContent  %+v", 204, o.Payload)
}

func (o *GetAllSellerProfileUsingGETNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllSellerProfileUsingGETBadRequest creates a GetAllSellerProfileUsingGETBadRequest with default headers values
func NewGetAllSellerProfileUsingGETBadRequest() *GetAllSellerProfileUsingGETBadRequest {
	return &GetAllSellerProfileUsingGETBadRequest{}
}

/*GetAllSellerProfileUsingGETBadRequest handles this case with default header values.

Bad Request
*/
type GetAllSellerProfileUsingGETBadRequest struct {
	Payload models.ErrorResponseArray
}

func (o *GetAllSellerProfileUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles][%d] getAllSellerProfileUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetAllSellerProfileUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllSellerProfileUsingGETNotFound creates a GetAllSellerProfileUsingGETNotFound with default headers values
func NewGetAllSellerProfileUsingGETNotFound() *GetAllSellerProfileUsingGETNotFound {
	return &GetAllSellerProfileUsingGETNotFound{}
}

/*GetAllSellerProfileUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetAllSellerProfileUsingGETNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetAllSellerProfileUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles][%d] getAllSellerProfileUsingGETNotFound  %+v", 404, o.Payload)
}

func (o *GetAllSellerProfileUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllSellerProfileUsingGETInternalServerError creates a GetAllSellerProfileUsingGETInternalServerError with default headers values
func NewGetAllSellerProfileUsingGETInternalServerError() *GetAllSellerProfileUsingGETInternalServerError {
	return &GetAllSellerProfileUsingGETInternalServerError{}
}

/*GetAllSellerProfileUsingGETInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAllSellerProfileUsingGETInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetAllSellerProfileUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ecx/v3/l2/serviceprofiles][%d] getAllSellerProfileUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAllSellerProfileUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
