// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProfileByIDOrNameUsingGETParams creates a new GetProfileByIDOrNameUsingGETParams object
// with the default values initialized.
func NewGetProfileByIDOrNameUsingGETParams() *GetProfileByIDOrNameUsingGETParams {
	var ()
	return &GetProfileByIDOrNameUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProfileByIDOrNameUsingGETParamsWithTimeout creates a new GetProfileByIDOrNameUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProfileByIDOrNameUsingGETParamsWithTimeout(timeout time.Duration) *GetProfileByIDOrNameUsingGETParams {
	var ()
	return &GetProfileByIDOrNameUsingGETParams{

		timeout: timeout,
	}
}

// NewGetProfileByIDOrNameUsingGETParamsWithContext creates a new GetProfileByIDOrNameUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProfileByIDOrNameUsingGETParamsWithContext(ctx context.Context) *GetProfileByIDOrNameUsingGETParams {
	var ()
	return &GetProfileByIDOrNameUsingGETParams{

		Context: ctx,
	}
}

// NewGetProfileByIDOrNameUsingGETParamsWithHTTPClient creates a new GetProfileByIDOrNameUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProfileByIDOrNameUsingGETParamsWithHTTPClient(client *http.Client) *GetProfileByIDOrNameUsingGETParams {
	var ()
	return &GetProfileByIDOrNameUsingGETParams{
		HTTPClient: client,
	}
}

/*GetProfileByIDOrNameUsingGETParams contains all the parameters to send to the API endpoint
for the get profile by Id or name using g e t operation typically these are written to a http.Request
*/
type GetProfileByIDOrNameUsingGETParams struct {

	/*Authorization
	  Specify the OAuth Bearer token with prefix 'Bearer '.

	*/
	Authorization string
	/*UUID
	  service profile uuid

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) WithTimeout(timeout time.Duration) *GetProfileByIDOrNameUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) WithContext(ctx context.Context) *GetProfileByIDOrNameUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) WithHTTPClient(client *http.Client) *GetProfileByIDOrNameUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) WithAuthorization(authorization string) *GetProfileByIDOrNameUsingGETParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithUUID adds the uuid to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) WithUUID(uuid string) *GetProfileByIDOrNameUsingGETParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get profile by Id or name using g e t params
func (o *GetProfileByIDOrNameUsingGETParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetProfileByIDOrNameUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
