// Code generated by go-swagger; DO NOT EDIT.

package service_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewValidateIntegrationIDUsingGETParams creates a new ValidateIntegrationIDUsingGETParams object
// with the default values initialized.
func NewValidateIntegrationIDUsingGETParams() *ValidateIntegrationIDUsingGETParams {
	var ()
	return &ValidateIntegrationIDUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateIntegrationIDUsingGETParamsWithTimeout creates a new ValidateIntegrationIDUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateIntegrationIDUsingGETParamsWithTimeout(timeout time.Duration) *ValidateIntegrationIDUsingGETParams {
	var ()
	return &ValidateIntegrationIDUsingGETParams{

		timeout: timeout,
	}
}

// NewValidateIntegrationIDUsingGETParamsWithContext creates a new ValidateIntegrationIDUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateIntegrationIDUsingGETParamsWithContext(ctx context.Context) *ValidateIntegrationIDUsingGETParams {
	var ()
	return &ValidateIntegrationIDUsingGETParams{

		Context: ctx,
	}
}

// NewValidateIntegrationIDUsingGETParamsWithHTTPClient creates a new ValidateIntegrationIDUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateIntegrationIDUsingGETParamsWithHTTPClient(client *http.Client) *ValidateIntegrationIDUsingGETParams {
	var ()
	return &ValidateIntegrationIDUsingGETParams{
		HTTPClient: client,
	}
}

/*ValidateIntegrationIDUsingGETParams contains all the parameters to send to the API endpoint
for the validate integration Id using g e t operation typically these are written to a http.Request
*/
type ValidateIntegrationIDUsingGETParams struct {

	/*Authorization
	  Specify the OAuth Bearer token with prefix 'Bearer '.

	*/
	Authorization string
	/*IntegrationID
	  integrationId

	*/
	IntegrationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) WithTimeout(timeout time.Duration) *ValidateIntegrationIDUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) WithContext(ctx context.Context) *ValidateIntegrationIDUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) WithHTTPClient(client *http.Client) *ValidateIntegrationIDUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) WithAuthorization(authorization string) *ValidateIntegrationIDUsingGETParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithIntegrationID adds the integrationID to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) WithIntegrationID(integrationID string) *ValidateIntegrationIDUsingGETParams {
	o.SetIntegrationID(integrationID)
	return o
}

// SetIntegrationID adds the integrationId to the validate integration Id using g e t params
func (o *ValidateIntegrationIDUsingGETParams) SetIntegrationID(integrationID string) {
	o.IntegrationID = integrationID
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateIntegrationIDUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param integrationId
	if err := r.SetPathParam("integrationId", o.IntegrationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
