// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BuyerPreferenceModel buyer preference model
// swagger:model BuyerPreferenceModel
type BuyerPreferenceModel struct {

	// emails
	Emails []string `json:"emails"`

	// port threshold
	PortThreshold int32 `json:"portThreshold,omitempty"`
}

// Validate validates this buyer preference model
func (m *BuyerPreferenceModel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BuyerPreferenceModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuyerPreferenceModel) UnmarshalBinary(b []byte) error {
	var res BuyerPreferenceModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
