// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ConnectorExistenceResponse connector existence response
// swagger:model ConnectorExistenceResponse
type ConnectorExistenceResponse struct {

	// exist
	Exist bool `json:"exist,omitempty"`
}

// Validate validates this connector existence response
func (m *ConnectorExistenceResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConnectorExistenceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectorExistenceResponse) UnmarshalBinary(b []byte) error {
	var res ConnectorExistenceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
