// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetServProfServicesRespContentMetros get serv prof services resp content metros
// swagger:model GetServProfServicesRespContentMetros
type GetServProfServicesRespContentMetros struct {

	// code
	Code string `json:"code,omitempty"`

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// ibxs
	Ibxs []string `json:"ibxs"`

	// in trail
	InTrail bool `json:"inTrail,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this get serv prof services resp content metros
func (m *GetServProfServicesRespContentMetros) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetServProfServicesRespContentMetros) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetServProfServicesRespContentMetros) UnmarshalBinary(b []byte) error {
	var res GetServProfServicesRespContentMetros
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
