// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PatchactionRequiredData patchaction required data
// swagger:model PatchactionRequiredData
type PatchactionRequiredData struct {

	// editable
	Editable bool `json:"editable,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// validation pattern
	ValidationPattern string `json:"validationPattern,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this patchaction required data
func (m *PatchactionRequiredData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchactionRequiredData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchactionRequiredData) UnmarshalBinary(b []byte) error {
	var res PatchactionRequiredData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
