// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RIOptionalNetwork r i optional network
// swagger:model RIOptionalNetwork
type RIOptionalNetwork struct {

	// cm metros
	CmMetros []string `json:"cm_metros"`

	// filter incoming routes
	FilterIncomingRoutes bool `json:"filter_incoming_routes,omitempty"`

	// prefix size
	PrefixSize float64 `json:"prefix_size,omitempty"`

	// seller config
	SellerConfig bool `json:"seller_config,omitempty"`
}

// Validate validates this r i optional network
func (m *RIOptionalNetwork) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RIOptionalNetwork) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RIOptionalNetwork) UnmarshalBinary(b []byte) error {
	var res RIOptionalNetwork
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
