// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RiServiceProfile ri service profile
// swagger:model RiServiceProfile
type RiServiceProfile struct {

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// created date
	CreatedDate string `json:"createdDate,omitempty"`

	// last updated by
	LastUpdatedBy string `json:"lastUpdatedBy,omitempty"`

	// last updated date
	LastUpdatedDate string `json:"lastUpdatedDate,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// optional network services
	OptionalNetworkServices *RiServiceProfileOptionalNetwork `json:"optionalNetworkServices,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this ri service profile
func (m *RiServiceProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOptionalNetworkServices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RiServiceProfile) validateOptionalNetworkServices(formats strfmt.Registry) error {

	if swag.IsZero(m.OptionalNetworkServices) { // not required
		return nil
	}

	if m.OptionalNetworkServices != nil {
		if err := m.OptionalNetworkServices.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("optionalNetworkServices")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RiServiceProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RiServiceProfile) UnmarshalBinary(b []byte) error {
	var res RiServiceProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
