// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RoutingInstanceCreateRequest routing instance create request
// swagger:model RoutingInstanceCreateRequest
type RoutingInstanceCreateRequest struct {

	// asn
	Asn int64 `json:"asn,omitempty"`

	// bgp authorization key
	BgpAuthorizationKey string `json:"bgpAuthorizationKey,omitempty"`

	// metro code
	MetroCode string `json:"metroCode,omitempty"`

	// notification emails
	NotificationEmails []string `json:"notificationEmails"`

	// primary r i name
	PrimaryRIName string `json:"primaryRIName,omitempty"`

	// route type
	RouteType string `json:"routeType,omitempty"`

	// secondary r i name
	SecondaryRIName string `json:"secondaryRIName,omitempty"`
}

// Validate validates this routing instance create request
func (m *RoutingInstanceCreateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoutingInstanceCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoutingInstanceCreateRequest) UnmarshalBinary(b []byte) error {
	var res RoutingInstanceCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
