// Code generated by go-swagger; DO NOT EDIT.

package buyer_preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jxoir/go-ecxfabric/models"
)

// SaveBuyerPreferenceUsingPOSTReader is a Reader for the SaveBuyerPreferenceUsingPOST structure.
type SaveBuyerPreferenceUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SaveBuyerPreferenceUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSaveBuyerPreferenceUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSaveBuyerPreferenceUsingPOSTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewSaveBuyerPreferenceUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewSaveBuyerPreferenceUsingPOSTInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSaveBuyerPreferenceUsingPOSTOK creates a SaveBuyerPreferenceUsingPOSTOK with default headers values
func NewSaveBuyerPreferenceUsingPOSTOK() *SaveBuyerPreferenceUsingPOSTOK {
	return &SaveBuyerPreferenceUsingPOSTOK{}
}

/*SaveBuyerPreferenceUsingPOSTOK handles this case with default header values.

Success
*/
type SaveBuyerPreferenceUsingPOSTOK struct {
	Payload *models.BuyerPreferenceModel
}

func (o *SaveBuyerPreferenceUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l2/buyerPreference][%d] saveBuyerPreferenceUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *SaveBuyerPreferenceUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BuyerPreferenceModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveBuyerPreferenceUsingPOSTBadRequest creates a SaveBuyerPreferenceUsingPOSTBadRequest with default headers values
func NewSaveBuyerPreferenceUsingPOSTBadRequest() *SaveBuyerPreferenceUsingPOSTBadRequest {
	return &SaveBuyerPreferenceUsingPOSTBadRequest{}
}

/*SaveBuyerPreferenceUsingPOSTBadRequest handles this case with default header values.

Record Not Found
*/
type SaveBuyerPreferenceUsingPOSTBadRequest struct {
	Payload models.ErrorResponseArray
}

func (o *SaveBuyerPreferenceUsingPOSTBadRequest) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l2/buyerPreference][%d] saveBuyerPreferenceUsingPOSTBadRequest  %+v", 400, o.Payload)
}

func (o *SaveBuyerPreferenceUsingPOSTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveBuyerPreferenceUsingPOSTNotFound creates a SaveBuyerPreferenceUsingPOSTNotFound with default headers values
func NewSaveBuyerPreferenceUsingPOSTNotFound() *SaveBuyerPreferenceUsingPOSTNotFound {
	return &SaveBuyerPreferenceUsingPOSTNotFound{}
}

/*SaveBuyerPreferenceUsingPOSTNotFound handles this case with default header values.

Record Not Found
*/
type SaveBuyerPreferenceUsingPOSTNotFound struct {
	Payload *models.ErrorResponse
}

func (o *SaveBuyerPreferenceUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l2/buyerPreference][%d] saveBuyerPreferenceUsingPOSTNotFound  %+v", 404, o.Payload)
}

func (o *SaveBuyerPreferenceUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveBuyerPreferenceUsingPOSTInternalServerError creates a SaveBuyerPreferenceUsingPOSTInternalServerError with default headers values
func NewSaveBuyerPreferenceUsingPOSTInternalServerError() *SaveBuyerPreferenceUsingPOSTInternalServerError {
	return &SaveBuyerPreferenceUsingPOSTInternalServerError{}
}

/*SaveBuyerPreferenceUsingPOSTInternalServerError handles this case with default header values.

Internal Server Error
*/
type SaveBuyerPreferenceUsingPOSTInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *SaveBuyerPreferenceUsingPOSTInternalServerError) Error() string {
	return fmt.Sprintf("[POST /ecx/v3/l2/buyerPreference][%d] saveBuyerPreferenceUsingPOSTInternalServerError  %+v", 500, o.Payload)
}

func (o *SaveBuyerPreferenceUsingPOSTInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
