// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EquinixRegion equinix region
// swagger:model EquinixRegion
type EquinixRegion struct {

	// interconnection region
	InterconnectionRegion string `json:"interconnectionRegion,omitempty"`

	// region data
	RegionData []*SellerRegion `json:"regionData"`
}

// Validate validates this equinix region
func (m *EquinixRegion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegionData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EquinixRegion) validateRegionData(formats strfmt.Registry) error {

	if swag.IsZero(m.RegionData) { // not required
		return nil
	}

	for i := 0; i < len(m.RegionData); i++ {
		if swag.IsZero(m.RegionData[i]) { // not required
			continue
		}

		if m.RegionData[i] != nil {
			if err := m.RegionData[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("regionData" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EquinixRegion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EquinixRegion) UnmarshalBinary(b []byte) error {
	var res EquinixRegion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
