// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetsellerConResContentMetadata getseller con res content metadata
// swagger:model GetsellerConResContentMetadata
type GetsellerConResContentMetadata struct {

	// notification emails
	NotificationEmails []string `json:"notification_emails"`
}

// Validate validates this getseller con res content metadata
func (m *GetsellerConResContentMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetsellerConResContentMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetsellerConResContentMetadata) UnmarshalBinary(b []byte) error {
	var res GetsellerConResContentMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
