// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PortDetail port detail
// swagger:model PortDetail
type PortDetail struct {

	// cross connect Id
	CrossConnectID string `json:"crossConnectId,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// in trail
	InTrail bool `json:"inTrail,omitempty"`

	// metro code
	MetroCode string `json:"metroCode,omitempty"`

	// seller region
	SellerRegion string `json:"sellerRegion,omitempty"`

	// seller region description
	SellerRegionDescription string `json:"sellerRegionDescription,omitempty"`

	// xa
	Xa interface{} `json:"xa,omitempty"`
}

// Validate validates this port detail
func (m *PortDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PortDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortDetail) UnmarshalBinary(b []byte) error {
	var res PortDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
