// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RoutingInstanceDetailsv3 routing instance detailsv3
// swagger:model routingInstanceDetailsv3
type RoutingInstanceDetailsv3 struct {

	// id
	ID string `json:"id,omitempty"`

	// metro
	Metro string `json:"metro,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// seller region
	SellerRegion string `json:"sellerRegion,omitempty"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this routing instance detailsv3
func (m *RoutingInstanceDetailsv3) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoutingInstanceDetailsv3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoutingInstanceDetailsv3) UnmarshalBinary(b []byte) error {
	var res RoutingInstanceDetailsv3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
