// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ValidateIntegrationIDResponse validate integration Id response
// swagger:model ValidateIntegrationIdResponse
type ValidateIntegrationIDResponse struct {

	// message
	Message string `json:"message,omitempty"`

	// metadata
	Metadata []*Metadata `json:"metadata"`

	// redundancy
	Redundancy string `json:"redundancy,omitempty"`

	// seller regions
	SellerRegions []*EquinixRegion `json:"sellerRegions"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this validate integration Id response
func (m *ValidateIntegrationIDResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSellerRegions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidateIntegrationIDResponse) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	for i := 0; i < len(m.Metadata); i++ {
		if swag.IsZero(m.Metadata[i]) { // not required
			continue
		}

		if m.Metadata[i] != nil {
			if err := m.Metadata[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("metadata" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ValidateIntegrationIDResponse) validateSellerRegions(formats strfmt.Registry) error {

	if swag.IsZero(m.SellerRegions) { // not required
		return nil
	}

	for i := 0; i < len(m.SellerRegions); i++ {
		if swag.IsZero(m.SellerRegions[i]) { // not required
			continue
		}

		if m.SellerRegions[i] != nil {
			if err := m.SellerRegions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sellerRegions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ValidateIntegrationIDResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidateIntegrationIDResponse) UnmarshalBinary(b []byte) error {
	var res ValidateIntegrationIDResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
