// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GETCommonMetroResp g e t common metro resp
// swagger:model GETCommonMetroResp
type GETCommonMetroResp struct {

	// cloud reach
	CloudReach interface{} `json:"cloudReach,omitempty"`

	// code
	Code string `json:"code,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// region
	Region string `json:"region,omitempty"`
}

// Validate validates this g e t common metro resp
func (m *GETCommonMetroResp) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GETCommonMetroResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GETCommonMetroResp) UnmarshalBinary(b []byte) error {
	var res GETCommonMetroResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
