// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetServProfServicesRespContent get serv prof services resp content
// swagger:model GetServProfServicesRespContent
type GetServProfServicesRespContent struct {

	// allow custom speed
	AllowCustomSpeed bool `json:"allowCustomSpeed,omitempty"`

	// api available
	APIAvailable bool `json:"apiAvailable,omitempty"`

	// auth key label
	AuthKeyLabel string `json:"authKeyLabel,omitempty"`

	// authorization key
	AuthorizationKey string `json:"authorizationKey,omitempty"`

	// connection name label
	ConnectionNameLabel string `json:"connectionNameLabel,omitempty"`

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// created date
	CreatedDate string `json:"createdDate,omitempty"`

	// ctag label
	CtagLabel string `json:"ctagLabel,omitempty"`

	// features
	Features *GetServProfServicesRespContentfeatures `json:"features,omitempty"`

	// last updated by
	LastUpdatedBy string `json:"lastUpdatedBy,omitempty"`

	// last updated date
	LastUpdatedDate string `json:"lastUpdatedDate,omitempty"`

	// metros
	Metros *GetServProfServicesRespContentMetros `json:"metros,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organization name
	OrganizationName string `json:"organizationName,omitempty"`

	// private
	Private bool `json:"private,omitempty"`

	// profile encapsulation
	ProfileEncapsulation string `json:"profileEncapsulation,omitempty"`

	// required redundancy
	RequiredRedundancy bool `json:"requiredRedundancy,omitempty"`

	// self profile
	SelfProfile bool `json:"selfProfile,omitempty"`

	// speed bands
	SpeedBands []*SpeedBand `json:"speedBands"`

	// tag type
	TagType string `json:"tagType,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`

	// vlan same as primary
	VlanSameAsPrimary bool `json:"vlanSameAsPrimary,omitempty"`
}

// Validate validates this get serv prof services resp content
func (m *GetServProfServicesRespContent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeatures(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetros(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSpeedBands(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetServProfServicesRespContent) validateFeatures(formats strfmt.Registry) error {

	if swag.IsZero(m.Features) { // not required
		return nil
	}

	if m.Features != nil {
		if err := m.Features.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("features")
			}
			return err
		}
	}

	return nil
}

func (m *GetServProfServicesRespContent) validateMetros(formats strfmt.Registry) error {

	if swag.IsZero(m.Metros) { // not required
		return nil
	}

	if m.Metros != nil {
		if err := m.Metros.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metros")
			}
			return err
		}
	}

	return nil
}

func (m *GetServProfServicesRespContent) validateSpeedBands(formats strfmt.Registry) error {

	if swag.IsZero(m.SpeedBands) { // not required
		return nil
	}

	for i := 0; i < len(m.SpeedBands); i++ {
		if swag.IsZero(m.SpeedBands[i]) { // not required
			continue
		}

		if m.SpeedBands[i] != nil {
			if err := m.SpeedBands[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("speedBands" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetServProfServicesRespContent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetServProfServicesRespContent) UnmarshalBinary(b []byte) error {
	var res GetServProfServicesRespContent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
