// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetSellerServiceResponse get seller service response
// swagger:model GetSellerServiceResponse
type GetSellerServiceResponse struct {

	// page number
	PageNumber int64 `json:"pageNumber,omitempty"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`

	// seller services
	SellerServices []*SellerService `json:"sellerServices"`

	// total count
	TotalCount int64 `json:"totalCount,omitempty"`
}

// Validate validates this get seller service response
func (m *GetSellerServiceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSellerServices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSellerServiceResponse) validateSellerServices(formats strfmt.Registry) error {

	if swag.IsZero(m.SellerServices) { // not required
		return nil
	}

	for i := 0; i < len(m.SellerServices); i++ {
		if swag.IsZero(m.SellerServices[i]) { // not required
			continue
		}

		if m.SellerServices[i] != nil {
			if err := m.SellerServices[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sellerServices" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetSellerServiceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSellerServiceResponse) UnmarshalBinary(b []byte) error {
	var res GetSellerServiceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
