// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RoutingInstanceBundleOrdering routing instance bundle ordering
// swagger:model RoutingInstanceBundleOrdering
type RoutingInstanceBundleOrdering struct {

	// asn
	Asn int64 `json:"asn,omitempty"`

	// bgp authorization key
	BgpAuthorizationKey string `json:"bgpAuthorizationKey,omitempty"`

	// metro code
	MetroCode string `json:"metroCode,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// notification emails
	NotificationEmails []string `json:"notificationEmails"`

	// route type
	RouteType string `json:"routeType,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this routing instance bundle ordering
func (m *RoutingInstanceBundleOrdering) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoutingInstanceBundleOrdering) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoutingInstanceBundleOrdering) UnmarshalBinary(b []byte) error {
	var res RoutingInstanceBundleOrdering
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
