// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SellerServiceMetro seller service metro
// swagger:model SellerServiceMetro
type SellerServiceMetro struct {

	// code
	Code string `json:"code,omitempty"`
}

// Validate validates this seller service metro
func (m *SellerServiceMetro) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SellerServiceMetro) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SellerServiceMetro) UnmarshalBinary(b []byte) error {
	var res SellerServiceMetro
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
